### ISSUE TITLE
Broken link to debug spec

### ISSUE THREAD

**Issue by fafa1971** [westerndigitalcorporation/swerv_eh1#1]
The Reference Documents section of the PDF manual reports this link to the "RISC-V External Debug Support" specification:

* https://github.com/riscv/riscv-debug-spec/blob/master/riscv-debug-spec.pdf

This link is currently broken, and should be replaced with this one instead:

* https://github.com/riscv/riscv-debug-spec/blob/master/riscv-debug-release.pdf

Other than that, thanks for all the great work you guys are doing!  :-)

**Comment by tmw-wdc** [comment]
Thank you very much for your feedback Fabrizio!  The link will be fixed in the next release of the spec.

**Comment by AngelTerrones** [comment]
Hi all.

Both links are broken rn :(
The link to the last release is this one: 

- https://github.com/riscv/riscv-debug-spec/blob/release/riscv-debug-release.pdf

And for the draft:

- https://github.com/riscv/riscv-debug-spec/blob/master/riscv-debug-draft.pdf

**Comment by tmw-wdc** [comment]
Thank you very much for pointing out that the link has changed again Ángel!  It will be fixed in the next release of our spec.

**Comment by tmw-wdc** [comment]
The link has been fixed.
