### ISSUE TITLE
Request for simple code generation reference

### ISSUE THREAD

**Issue by rvgp** [westerndigitalcorporation/swerv_eh1#10]
Thanks for sharing this very impressing project. 

Will it be possible to share  a simple code generation reference (from C/ASM to HEX) Such as used for generating the provided Hello-World Hex files.  

More specifically I'm looking for the the boot code sequence performing initialization followed by load of the external code over the AHB and execution from the ICCM.

I manage to compile, load and execute some code, however it looks from the trace output that it is running extremely slow in terms of executed instructions per cycle (order of 0.1, stalled 90% of the cycles) even after the entire code is loaded and executing from the ICCM while the HELLO WORLD provided example  runs at reasonable performance, therefore I assume I’m missing something in my initialization sequence which I can’t figure out.

Udi

**Comment by olofk** [comment]
If it helps, I disassembled the hello world example some time ago. Here's the listing (the rest of the file is just filled with nop)

    00000000 <_binary_program_bin_start>:
       0:	b0219173          	csrrw	sp,minstret,gp
       4:	ee0002b7          	lui	t0,0xee000
       8:	0002e293          	ori	t0,t0,0
       c:	30529173          	csrrw	sp,mtvec,t0
      10:	5d555337          	lui	t1,0x5d555
      14:	55536313          	ori	t1,t1,1365
      18:	7c0310f3          	csrrw	ra,0x7c0,t1
      1c:	000002b7          	lui	t0,0x0
      20:	0002e293          	ori	t0,t0,0
      24:	7f829173          	csrrw	sp,0x7f8,t0
      28:	000002b7          	lui	t0,0x0
      2c:	0002e293          	ori	t0,t0,0
      30:	7f929173          	csrrw	sp,0x7f9,t0
      34:	00000013          	nop
      38:	f0040537          	lui	a0,0xf0040
      3c:	00056513          	ori	a0,a0,0
      40:	00100013          	li	zero,1
      44:	000004b7          	lui	s1,0x0
      48:	04806493          	ori	s1,zero,72
      4c:	00108093          	addi	ra,ra,1
      50:	00108093          	addi	ra,ra,1
      54:	d05805b7          	lui	a1,0xd0580
      58:	0005e593          	ori	a1,a1,0
      5c:	000004b7          	lui	s1,0x0
      60:	0484e493          	ori	s1,s1,72
      64:	0095a023          	sw	s1,0(a1) # d0580000 <_binary_program_bin_end+0xd057fce8>
      68:	000004b7          	lui	s1,0x0
      6c:	0454e493          	ori	s1,s1,69
      70:	0095a023          	sw	s1,0(a1)
      74:	00000013          	nop
      78:	00748493          	addi	s1,s1,7 # 7 <_binary_program_bin_start+0x7>
      7c:	00000013          	nop
      80:	0095a023          	sw	s1,0(a1)
      84:	00000013          	nop
      88:	0095a023          	sw	s1,0(a1)
      8c:	00000013          	nop
      90:	00000013          	nop
      94:	00348493          	addi	s1,s1,3
      98:	00000013          	nop
      9c:	00000013          	nop
      a0:	0095a023          	sw	s1,0(a1)
      a4:	00000013          	nop
      a8:	00000013          	nop
      ac:	00000013          	nop
      b0:	000004b7          	lui	s1,0x0
      b4:	0204e493          	ori	s1,s1,32
      b8:	00000013          	nop
      bc:	0095a023          	sw	s1,0(a1)
      c0:	00000013          	nop
      c4:	03748493          	addi	s1,s1,55 # 37 <_binary_program_bin_start+0x37>
      c8:	0095a023          	sw	s1,0(a1)
      cc:	000004b7          	lui	s1,0x0
      d0:	04f4e493          	ori	s1,s1,79
      d4:	0095a023          	sw	s1,0(a1)
      d8:	00348493          	addi	s1,s1,3 # 3 <_binary_program_bin_start+0x3>
      dc:	0095a023          	sw	s1,0(a1)
      e0:	000004b7          	lui	s1,0x0
      e4:	04c4e493          	ori	s1,s1,76
      e8:	0095a023          	sw	s1,0(a1)
      ec:	000004b7          	lui	s1,0x0
      f0:	0444e493          	ori	s1,s1,68
      f4:	0095a023          	sw	s1,0(a1)

**Comment by aprnath** [comment]
Hi Udi,
Thank you for your interest. We will provide the code reference shortly. Minimally you must write the MRAC CSR to enable the i-cache. We typically write 0x55555555 to enable icache for all regions.

To execute code from ICCM you need to either pre-load it (via a testbench  mechanism) or use the DMA slave port to load instructions to ICCM. The DCCM can be loaded via a memcopy() operation, in addition to the testbench and DMA methods.

**Comment by rvgp** [comment]
Many thanks for both useful replies, I now manage to nicely run with the cache enabled as well as directly from the ICCM, looking forward to the mentioned code reference.

Udi.

**Comment by aprnath** [comment]
Udi, I have updated the testbench to be a little more robust. Also added example assembly tests.
You should be able to run your own simple assembly tests using the instructions in the README.

**Comment by rvgp** [comment]
Thanks, that is useful.
Udi
