### ISSUE TITLE
Compiler option for CoreMark 

### ISSUE THREAD

**Issue by lance91633** [westerndigitalcorporation/swerv_eh1#14]
I have tried running CoreMark on the simulator with below options provided by Syntacore
`O3 -funroll-loops -fpeel-loops -fgcse-sm -fgcse-las `
However, the performance is up to 4.1 CM/MHz
Is there any suggestion about compiler option for better performance? 

Besides, is there any suggestion about hardware configuration or simulation mechanism for better performance?
Here is my hardware configuration and simulation mechanism
- Pre-load instruction in ICCM (Default size)
- I-cache enabled(Default configuration)(Using provided assembly code)
- Pre-load data in DCCM (Default size)

Thanks!

**Comment by robertgolla** [comment]
Lance, there are a couple of things to check to make sure you get the right CoreMark score from rtl simulation.

First thing is exactly how are you measuring cycles for one CoreMark loop iteration?

We use perf_start and perf_end labels as shown below in the C source:

	/* perform actual benchmark */
	start_time();

	__asm("__perf_start:");

#if (MULTITHREAD>1)
	if (default_num_contexts>MULTITHREAD) {
		default_num_contexts=MULTITHREAD;
	}
	for (i=0 ; i<default_num_contexts; i++) {
		results[i].iterations=results[0].iterations;
		results[i].execs=results[0].execs;
		core_start_parallel(&results[i]);
	}
	for (i=0 ; i<default_num_contexts; i++) {
		core_stop_parallel(&results[i]);
	}
#else
	iterate(&results[0]);
#endif

	__asm("__perf_end:");

	stop_time();
	total_time=get_time();

When we measure from perf_start to perf_end in rtl simulation with the following compiler flags “-O3 -funroll-all-loops fgcse-las”, we get a CM/MHz of around 4.6 for the default configuration of swerv core.  Our small cmark2.c example has 2 iterations, so calculation is (cycle_perf_end - cycle_perf_start) / 2 for 1 iteration of CoreMark.  

What do you get?

If I reconfigure the core to have more instruction cache, larger predictor

	./swerv.config -btb_size=512 -bht_size=2048 -icache_size=32

the score improves to around 4.9 CM/MHz.

**Comment by lance91633** [comment]
Hi Robert, 
Thank you for your respond. I stub the performance monitoring code snippet as same as yours. After you replied, I have changed my iteration number from 5 to 2. 

Now, the score is improved! However, there are some difference between my results and yours. When I use provided compiler option with default configuration, I got a CM/MHz of around  4.4. If I reconfigure the core as same as you provided, I got a CM/MHz of around 4.7. 

Maybe there are some difference between our memory mapping. I use the default memory mapping. Before simulation, I put the code section in ICCM(0xee000000), data section in DCCM(0xf0080000). 
In addition, I noticed that the default core configuration has no ICCM. Therefore, I tried to load instruction in external Instruction memory, but the score is similar. 

Besides, I tried to run Dhrystone benchmark with your hardware and compiler option. I got a DMIPS/MHz of around 2.2. Is there any other suggestion for running Dhrystone?

Thanks a lot for your response!

**Comment by jrahmeh** [comment]
Hi Lance,

We compiled core-marks with gcc 7.2.0 using the following flags: -O3 -funroll-all-loops -fgcse-sm -fgcse-las -mabi=ilp32 -march=rv32imc

We put all the source code of coremarks into one file.

Joe

**Comment by robertgolla** [comment]
btw, I think we need to figure out CoreMark before we switch over to Dhrystone.

Robert

**Comment by robertgolla** [comment]
Lance, if you don't mind email me at robert.t.golla@gmail.com.  Thanks.

**Comment by lance91633** [comment]
Robert,  

That would be helpful, I will contact you via email.

Thanks!

**Comment by lance91633** [comment]
The cause of mismatch is version of gcc 
When I switch my gcc version from 8.2 to 7.2, the performance is improved!

In original config: ~4.6CM/MHz
Larger i-cache and larger BTB/BHT : ~4.9CM/MHz

Thanks a lot!

**Comment by ZvonimirBandic** [comment]
Lance,
I would also quite appreciate if you publish your findings as some sort of
PDF "Application note" document, for future attempts on Coremark reqsult
replication.

Super thanks,
Z.
