### ISSUE TITLE
Does SweRV run RISCV 64-bit unit tests? Is there a configuration to enable that?

### ISSUE THREAD

**Issue by ksundara20** [westerndigitalcorporation/swerv_eh1#24]
I am able to compile RISCV tests in 32-bit mode and run them fine on SweRV RTL.
But when I run with 64-bit compiled tests, the Verilator behavior is unpredictable.
Not sure what is wrong. Need some guidance in setting the right configuration.

Krishna

**Comment by ZvonimirBandic** [comment]
Keep in mind that SweRV is 32IMC core - it is only 32-bit.

Z.

**Comment by ksundara20** [comment]
Hi Mr. Bandic, that explains it. But I am curious why that is not mentioned anywhere in the online documentation. I would appreciate it if you will add that to the README. Thanks.

**Comment by tmw-wdc** [comment]
Hi Krishna,

Please look at the overview chapter of the Programmer’s Reference Manual (PDF) for a list of the features supported by the SweRV EH1 core.

Kind regards,
Thomas

**Comment by jrahmeh** [comment]
I have updated the README file to state that SweRV 1 is a 32-bit, machine
mode only, implementation of RISC-V including options I, M, and C.
