### ISSUE TITLE
Get confused by doc 《RISC-V_SweRV_EH1_PRM.pdf》

### ISSUE THREAD

**Issue by walkingjian** [westerndigitalcorporation/swerv_eh1#35]
Hi，SwerV team
    I'm try swerv_eh1_fpga database, and I can compile the "helloworld" example build, but in this project，I'm confused by external ram base address,
        1.   "swerv_eh1_fpga/software/bsp/link.ld" show the ram(to contain .text .data .stack) ‘s base address is 0x0；
        2. doc 《RISC-V_SweRV_EH1_PRM.pdf》show that swerv core's address map in section 2.8, and the address 0x0~0x0fff_ffff contain ICCM/DCCM/Reserverd Section;
        so, is it all right that riscv tool-chain use 0x0 as the start address of extern ram in this build? I'm confused by this conflict, please give me some tip, thanks a lot from an RISCV fan

**Comment by tmw-wdc** [comment]
Hi!

Thank you for your question.  Please note that the open-source SweRV core repository has moved to [Chip Alliance](https://github.com/chipsalliance/Cores-SweRV) and this repository is deprecated.  Please post future questions and comments to the new repository.

Table 2-10 _SweRV EH1 Memory Address Map (Example)_ is just an example of a memory address map.  The core provides a lot of flexibility where in memory the different components may be placed, with some restrictions documented in Section 2.3.3.

Hope this helps.

Kind regards,
Thomas

**Comment by walkingjian** [comment]
> Hi!
> 
> Thank you for your question. Please note that the open-source SweRV core repository has moved to [Chip Alliance](https://github.com/chipsalliance/Cores-SweRV) and this repository is deprecated. Please post future questions and comments to the new repository.
> 
> Table 2-10 _SweRV EH1 Memory Address Map (Example)_ is just an example of a memory address map. The core provides a lot of flexibility where in memory the different components may be placed, with some restrictions documented in Section 2.3.3.
> 
> Hope this helps.
> 
> Kind regards,
> Thomas

Thanks a lot, and I get this repository from  "SweRV EH1" hyperlink in "https://riscv.org/risc-v-cores/"

**Comment by tmw-wdc** [comment]
Thank you for letting me know where you got the link to SweRV EH1 from.  I'll look into how to have this fixed on the riscv.org page.

Kind regards,
Thomas
