### ISSUE TITLE
Synthesis script template

### ISSUE THREAD

**Issue by kidonglee** [westerndigitalcorporation/swerv_eh1#37]
Hi, 

I am trying to synthesis swerv_eh1.
However it is not easy for me because swerv_eh1 is written in systemverilog.
I got some error messages which seem to be related to systemverilog syntax, such as package, typedef....
Is there a synthesis script template for design compiler ?

Thanks.

**Comment by aprnath** [comment]
This repository is deprecated. Please use the [CHIPS Alliance repository](https://github.com/chipsalliance/Cores-SweRV).
