### ISSUE TITLE
Syntax error in dmi_jtag_to_core_sync.v during vivado synthesis

### ISSUE THREAD

**Issue by kidonglee** [westerndigitalcorporation/swerv_eh1#38]
Hi,

During synthesis using vivado, I got syntax error messages on the following code.
```
// synchronizers  
always @ ( posedge clk or negedge rst_n) begin
    if(!rst_n) begin
        rden <= '0;  // --> rden <= 'd0;
        wren <= '0;  // --> wren <= 'd0;
    end
    else begin
        rden <= {rden[1:0], rd_en};
        wren <= {wren[1:0], wr_en};
    end
end
```
Please fix it.

Thanks

**Comment by aprnath** [comment]
This repository is deprecated. Please use the [CHIPS Alliance repository](https://github.com/chipsalliance/Cores-SweRV). The issue has been fixed there for a long time.
